### ISSUE TITLE
Migrate source code from CodePlex to here

### ISSUE THREAD

**Issue by Eilon** [aspnet/AspNetWebOptimization#1]
Need to copy all the codes and branches from http://aspnetoptimization.codeplex.com/ and import to here. CodePlex is shutting down very soon so we need to do this ASAP.

cc @ajcvickers

**Comment by HaoK** [comment]
Done via 97c61ab38948cef17bb0f641a7b216897b9082ad

I verified that the sln still builds and runs tests, there was only a single master branch on codeplex so there were no older versions to port.
